CREATE TABLE IF NOT EXISTS raw_forest_cover (
    id INT AUTO_INCREMENT PRIMARY KEY,
    elevation INT,
    aspect INT,
    slope INT,
    horizontal_distance_to_hydrology INT,
    vertical_distance_to_hydrology INT,
    horizontal_distance_to_roadways INT,
    hillshade_9am INT,
    hillshade_noon INT,
    hillshade_3pm INT,
    horizontal_distance_to_fire_points INT,
    wilderness_area_rawah INT,
    wilderness_area_neota INT,
    wilderness_area_comanche_peak INT,
    wilderness_area_cache_la_poudre INT,
    soil_type_c1 INT,
    soil_type_c2 INT,
    soil_type_c3 INT,
    soil_type_c4 INT,
    soil_type_c5 INT,
    soil_type_c6 INT,
    soil_type_c7 INT,
    soil_type_c8 INT,
    soil_type_c9 INT,
    soil_type_c10 INT,
    soil_type_c11 INT,
    soil_type_c12 INT,
    soil_type_c13 INT,
    soil_type_c14 INT,
    soil_type_c15 INT,
    soil_type_c16 INT,
    soil_type_c17 INT,
    soil_type_c18 INT,
    soil_type_c19 INT,
    soil_type_c20 INT,
    soil_type_c21 INT,
    soil_type_c22 INT,
    soil_type_c23 INT,
    soil_type_c24 INT,
    soil_type_c25 INT,
    soil_type_c26 INT,
    soil_type_c27 INT,
    soil_type_c28 INT,
    soil_type_c29 INT,
    soil_type_c30 INT,
    soil_type_c31 INT,
    soil_type_c32 INT,
    soil_type_c33 INT,
    soil_type_c34 INT,
    soil_type_c35 INT,
    soil_type_c36 INT,
    soil_type_c37 INT,
    soil_type_c38 INT,
    soil_type_c39 INT,
    soil_type_c40 INT,
    cover_type INT,
    group_id VARCHAR(20),
    ingestion_ts DATETIME
);

CREATE TABLE IF NOT EXISTS processed_forest_cover (
    id INT AUTO_INCREMENT PRIMARY KEY,
    elevation INT,
    aspect INT,
    slope INT,
    horizontal_distance_to_hydrology INT,
    vertical_distance_to_hydrology INT,
    horizontal_distance_to_roadways INT,
    hillshade_9am INT,
    hillshade_noon INT,
    hillshade_3pm INT,
    horizontal_distance_to_fire_points INT,
    wilderness_area VARCHAR(50),
    soil_type VARCHAR(10),
    cover_type INT
);

CREATE TABLE IF NOT EXISTS batch_log (
    id INT AUTO_INCREMENT PRIMARY KEY,
    batch_number INT NOT NULL,
    group_number INT NOT NULL,
    record_count INT NOT NULL,
    loaded_at DATETIME NOT NULL,
    UNIQUE KEY uq_batch_group (batch_number, group_number)
);
